### ISSUE TITLE
do you the finagle new api for zk?

### ISSUE THREAD

**Issue by 3thinkthendoit** [eirslett/thrift-zookeeper#1]
like this 

 //#thriftclientapi
    Hello.ServiceIface client = Thrift.newIface("localhost:8080", Hello.ServiceIface.class);
    Future<String> response = client.hello().onSuccess(new Function<String, BoxedUnit>() {
      @Override
      public BoxedUnit apply(String response) {
        System.out.println("Received response: " + response);
        return null;
      }
    });

   // response.raiseWithin(1.ms, timer)
    Await.result(response);

the zookeeper code 
 String zkPath = "/foo/bar/baz";
       ZkClientFactory cf = new ZkClientFactory(Duration.apply(5, TimeUnit.SECONDS));//10 seconds  
       ZkResolver zk  = new ZkResolver(cf);
       InetSocketAddress zookeeperAddress = new InetSocketAddress("192.168.115.105", 2181);
       ZooKeeperClient zookeeperClient = new ZooKeeperClient(Amount.of(10, Time.MILLISECONDS),zookeeperAddress);
       ServerSetImpl serverSet = new ServerSetImpl(zookeeperClient, zkPath);
       //add the servie to zookeeper
       InetSocketAddress endpoint1 = new InetSocketAddress("10.50.101.133", 1080);
       InetSocketAddress endpoint2 = new InetSocketAddress("10.50.101.133", 2090);
       try {
           EndpointStatus  status1 = serverSet.join(endpoint1, new HashMap<String,InetSocketAddress>(),Status.ALIVE);
           EndpointStatus  status2 = serverSet.join(endpoint2, new HashMap<String,InetSocketAddress>(),Status.ALIVE);
           ZkGroup cluster = new ZkGroup(serverSet, zkPath);// for client cluster ，get node info from zookeeper
           scala.collection.immutable.Set<ServiceInstance> set =  cluster.apply();
           System.out.println(set.size());
       } catch (JoinException e) {
            e.printStackTrace();
       } catch (InterruptedException e) {
            e.printStackTrace();
       }finally{
           zookeeperClient.close();
       }

**Comment by eirslett** [comment]
I guess this repository is ages old, and basically abandoned :wink:

**Comment by 3thinkthendoit** [comment]
@eirslett please  give me a demo of finagle api with zookeeper code by java.thank you....
